app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from app.views import index

urlpatterns = [
    path('', include('portal.urls')),
    path('admin/', admin.site.urls),
    #path('personal/', include('personals.urls')),
    #path('kvantums/', include('kvantums.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portal'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

    path('report/', views.report_all, name='report_all'),
    path('reports/<int:pk>', views.report_show, name='report_show'),

    path('staff/', views.staff_all, name='staff_all'),
    path('staffs/<int:pk>', views.staff_show, name='staff_show'),

    path('arrows/', views.arrow_all, name='arrows'),
    path('arrows/<int:pk>', views.arrow_show, name='context'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/models.py
from django.db import models


class PortalSettings(models.Model):
    portal_base_href = models.CharField(max_length=400, verbose_name="ссылка на сайт (корневая)")
    portal_title = models.CharField(max_length=400, verbose_name="Название портала")
    portal_keywords = models.CharField(max_length=1000, verbose_name="Ключевые слова")
    portal_description = models.CharField(max_length=1000, verbose_name="Примечания к сайту")

    class Meta:
        verbose_name = "Настройки портала"
        verbose_name_plural = "Настройки портала"

    def __str__(self):
        return self.portal_title


class Record(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.CharField(max_length=100)
	phone = models.CharField(max_length=15)
	address = models.CharField(max_length=100)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=50)
	zipcode = models.CharField(max_length=20)

	def __str__(self):
		return(f"{self.first_name} {self.last_name}")

portal/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="",
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш Email'}))
    first_name = forms.CharField(label="", max_length=100,
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите '}))
    last_name = forms.CharField(label="", max_length=100,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields[
            'username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields[
            'password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields[
            'password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


# Create Add Record Form
class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={"placeholder": "First Name", "class": "form-control"}), label="")
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(
        attrs={"placeholder": "Last Name", "class": "form-control"}), label="")
    email = forms.CharField(required=True,
                            widget=forms.widgets.TextInput(attrs={"placeholder": "Email", "class": "form-control"}),
                            label="")
    phone = forms.CharField(required=True,
                            widget=forms.widgets.TextInput(attrs={"placeholder": "Phone", "class": "form-control"}),
                            label="")
    address = forms.CharField(required=True,
                              widget=forms.widgets.TextInput(attrs={"placeholder": "Address", "class": "form-control"}),
                              label="")
    city = forms.CharField(required=True,
                           widget=forms.widgets.TextInput(attrs={"placeholder": "City", "class": "form-control"}),
                           label="")
    state = forms.CharField(required=True,
                            widget=forms.widgets.TextInput(attrs={"placeholder": "State", "class": "form-control"}),
                            label="")
    zipcode = forms.CharField(required=True,
                              widget=forms.widgets.TextInput(attrs={"placeholder": "Zipcode", "class": "form-control"}),
                              label="")

    class Meta:
        model = Record
        exclude = ("user",)

portal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from .forms import SignUpForm
from students.models import StudentTeacherReport
from personals.models import Staff, Teacher
from kvantums.models import Kvantum
from .models import PortalSettings


def home(request):
    # Настройки сайта
    #portal_title = PortalSettings.get()
    # Проверка на вход в систему
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # Авторизация
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Вы вошли в систему")
            return redirect('portal:home')
        else:
            messages.success(request, "Возника ошибка при входе систему")
            return redirect('portal:home')

    return render(request, 'home.html')


def login_user(request):
    pass


def logout_user(request):
    logout(request)
    messages.success(request, "Вы вышли из системы")
    return redirect('portal:home')


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate and login
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Вы удачно создали Ваш электронный профиль! Добро пожаловать!")
            return redirect('portal:home')
    else:
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})

    return render(request, 'register.html', {'form': form})


def report_all(request):
    if request.user.is_authenticated:
        try:
            report_alls = StudentTeacherReport.objects.all()
            arrows = Kvantum.objects.all()
            context = {"report_alls": report_alls, "arrows": arrows}
            return render(request, "report/reports.html", context)
        except ObjectDoesNotExist:
            messages.success(request, "Нет данных в базе.")
            return render(request, "report/reports.html")
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')


def report_show(request, pk):
    if request.user.is_authenticated:
        try:
            report_status = StudentTeacherReport.objects.get(id=pk)
            context = {'report_status': report_status}
            return render(request, 'report/report.html', context)
        except ObjectDoesNotExist:
            messages.success(request, "Нет данных в базе.")
            return render(request, 'report/report.html', )
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')


def staff_all(request):
    if request.user.is_authenticated:
        try:
            staff_alls = Teacher.objects.all()
            return render(request, "staff/show.html", {"staff_alls": staff_alls})
        except ObjectDoesNotExist:
            messages.success(request, "Нет данных в базе.")
            return render(request, "staff/show.html")
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')


def staff_show(request, pk):
    if request.user.is_authenticated:
        try:
            teacher_personals = Teacher.objects.get(id=pk)
            staff_personals = Staff.objects.get(id=pk)
            return render(request, 'staff/personal.html', {'staff_personals': staff_personals, 'teacher_personals': teacher_personals })
        except ObjectDoesNotExist:
            messages.success(request, "Нет преподавателя в базе.")
            return render(request, 'staff/personal.html', )
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')


def arrow_all(request):
    if request.user.is_authenticated:
        try:
            arrows = Kvantum.objects.all()
            context = {'arrows': arrows}
            return render(request, 'arrows/arrows.html', context)
        except ObjectDoesNotExist:
            messages.success(request, "Нет направления в базе.")
            return render(request, 'arrows/arrows.html', )
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')


def arrow_show(request, pk):
    if request.user.is_authenticated:
        try:
            # Apply basic filtering
            report_status = StudentTeacherReport.objects.filter(arrows_id='1')
            arrow_status = Kvantum.objects.get(id=pk)
            report_alls = StudentTeacherReport.objects.all()
            arrows = Kvantum.objects.all()
            #report_status = StudentTeacherReport.objects.get(id=pk)
            return render(request, 'arrows/show.html', {'report_status': report_status, 'arrow_status': arrow_status, 'report_alls': report_alls, 'arrows': arrows})
        except ObjectDoesNotExist:
            messages.success(request, "Нет данного направления в базе!")
            return render(request, 'arrows/show.html', )
    else:
        messages.success(request, "Нужно войти в систему чтобы увидеть данные...")
        return redirect('portal:home')

portal/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}MCRM{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
</head>
<body>
<div class="container">

    {% if messages %}
    {% for message in messages %}
    <br>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    {% endfor %}

    {% endif %}

    {% block content %}

    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
        crossorigin="anonymous"></script>
</body>
</html>

portal/templates/cards.html
<div class="card">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>

portal/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
{% include 'navbar.html' %}
<div class="col-md-6 offset-md-3">
    <h1>Добро пожаловать</h1>
    <div class="col-md-10 offset-md-1">
        {% include 'cards.html' %}
    </div>

    {% else %}
    <div class="col-md-6 offset-md-3">
        <h1>Авторизация</h1>
        <form method="POST" action="{% url 'portal:home' %}">
            {% csrf_token %}

            <form>
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Введите имя пользователя"
                           required>
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Введите ваш пароль"
                           required>
                </div>
                <!--            <div class="mb-3 form-check">-->
                <!--                <input type="checkbox" class="form-check-input" id="exampleCheck1">-->
                <!--                <label  class="form-check-label" for="exampleCheck1">Check me out</label>-->
                <!--            </div>-->
                <button type="submit" class="btn btn-secondary">Войти</button>
            </form>


        </form>
    </div>

    {% endif %}
    {% endblock %}

portal/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'portal:home' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <!--                <li class="nav-item">-->
                <!--                    <a class="nav-link active" aria-current="page" href="#">Home</a>-->
                <!--                </li>-->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:logout' %}">Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:arrows' %}">Направления</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Педагоги
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'portal:staff_all' %}">Состав</a></li>
                        <li><a class="dropdown-item" href="{% url 'portal:report_all' %}">Отчеты</a></li>
                        <!--                        <li>-->
                        <!--                            <hr class="dropdown-divider">-->
                        <!--                        </li>-->
                        <!--                        <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:home' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:register' %}">Зарегистрироваться</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

portal/templates/register.html
{% extends 'base.html' %}
{% block content %}


<div class="col-md-6 offset-md-3">
<h1>Регистрация</h1>
<br/>

<form method="POST" action="">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-secondary">Регистрация</button>
	</form>



</div>

{% endblock %}